# Generated by Django 5.2.8 on 2025-12-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Musaitlik', 'verbose_name_plural': 'Musaitlikler'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Öğrenci', 'verbose_name_plural': 'Öğrenciler'},
        ),
    ]
