# Generated by Django 5.2.8 on 2025-12-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevu',
            name='musaitlik',
        ),
        migrations.RemoveField(
            model_name='randevu',
            name='ogrenci',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='numara',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='unvan',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bolum',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('academician', 'Akademisyen'), ('student', 'Öğrenci')], default='student', max_length=15),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('academician', models.ForeignKey(limit_choices_to={'role': 'akademisyen'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('note_message', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.availability')),
            ],
        ),
        migrations.DeleteModel(
            name='Musaitlik',
        ),
        migrations.DeleteModel(
            name='Randevu',
        ),
    ]
